#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-openvpn-update event
#--------------------------------------------------

my $event = "nethserver-openvpn-update";

event_actions($event, 
    'initialize-default-databases' => '00',
    'nethserver-openvpn-delserver' => 30,
);
templates2events("/etc/openvpn/host-to-net.conf",  $event);
templates2events("/etc/openvpn/host-to-net.pool",  $event);
event_services($event, 'openvpn' => 'restart');

#--------------------------------------------------
# actions for nethserver-openvpn-save event
#--------------------------------------------------

$event = "nethserver-openvpn-save";

event_actions($event, 
    'nethserver-openvpn-delserver' => 30,
    'firewall-adjust' => '80',
    'trusted-networks-modify' => '95'
);
templates2events("/etc/openvpn/host-to-net.conf",  $event);
templates2events("/etc/openvpn/host-to-net.pool",  $event);
event_services($event, 'openvpn' => 'restart');


#--------------------------------------------------
# actions for interface-update event
#--------------------------------------------------

$event = "interface-update";

templates2events("/etc/openvpn/host-to-net.conf",  $event);
event_services($event, 'openvpn' => 'restart');


#--------------------------------------------------
# actions for static-routes-save event
#--------------------------------------------------

$event = "static-routes-save";

templates2events("/etc/openvpn/host-to-net.conf", $event);
event_services($event, 'openvpn' => 'restart');


#--------------------------------------------------
# actions for nethserver-vpn-create event
#--------------------------------------------------

$event = "nethserver-vpn-create";

event_actions($event,
    'nethserver-openvpn-genclient' => '30',
);

event_services($event, 'openvpn' => 'restart');


#--------------------------------------------------
# actions for nethserver-vpn-modify event
#--------------------------------------------------

$event = "nethserver-vpn-modify";

event_actions($event,
    'nethserver-openvpn-genclient' => '30',
);

event_services($event, 'openvpn' => 'restart');

#--------------------------------------------------
# actions for nethserver-vpn-delete event
#--------------------------------------------------

$event = "nethserver-vpn-delete";

event_actions($event,
    'nethserver-openvpn-delclient' => '30',
);

event_services($event, 'openvpn' => 'restart');

#--------------------------------------------------
# actions for nethserver-vpn-save event
#--------------------------------------------------

$event = "nethserver-vpn-save";

event_actions($event,
    'nethserver-openvpn-delserver' => 20,
    'nethserver-openvpn-net2net' => '30',
    'trusted-networks-modify' => '95'
);

event_services($event, 'openvpn' => 'restart');
templates2events("/etc/openvpn/host-to-net.conf",  $event);

