#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-openvpn-update event
#--------------------------------------------------

my $event = "nethserver-openvpn-update";

event_actions($event, 
    'initialize-default-databases' => '00',
    'nethserver-openvpn-adjust-certs-permissions' => '10',
    'nethserver-vpn-conf' => '20',
    'nethserver-openvpn-crl' => '30',
    'nethserver-openvpn-net2net' => '40',
    'nethserver-openvpn-create-connections-db' => '50',
);
templates2events("/etc/pam.d/openvpn-otp",  $event);
templates2events("/etc/openvpn/host-to-net.conf",  $event);
templates2events("/etc/openvpn/host-to-net.pool",  $event);
templates2events("/var/lib/nethserver/certs/ca.cnf",  $event);
templates2events("/etc/sudoers",  $event);
event_services($event, 'openvpn@host-to-net' => 'restart');

#--------------------------------------------------
# actions for nethserver-openvpn-save event
#--------------------------------------------------

$event = "nethserver-openvpn-save";

event_actions($event,
    'firewall-adjust' => '80',
    'trusted-networks-modify' => '95'
);
templates2events("/etc/pam.d/openvpn-otp",  $event);
templates2events("/etc/openvpn/host-to-net.conf",  $event);
templates2events("/etc/openvpn/host-to-net.pool",  $event);
event_services($event, 'openvpn@host-to-net' => 'restart');


#--------------------------------------------------
# actions for interface-update event
#--------------------------------------------------

$event = "interface-update";

templates2events("/etc/openvpn/host-to-net.conf",  $event);
event_services($event, 'openvpn@host-to-net' => 'restart');
event_actions($event,
    'nethserver-openvpn-restart-tunnels' => '80',
);


#--------------------------------------------------
# actions for static-routes-save event
#--------------------------------------------------

$event = "static-routes-save";

templates2events("/etc/openvpn/host-to-net.conf", $event);
event_services($event, 'openvpn@host-to-net' => 'restart');



#--------------------------------------------------
# actions for nethserver-vpn-save event
#--------------------------------------------------

$event = "nethserver-vpn-save";

event_actions($event,
    'nethserver-openvpn-net2net' => '30',
    'trusted-networks-modify' => '95'
);

event_services($event, 'openvpn@host-to-net' => 'restart');
templates2events("/etc/openvpn/host-to-net.conf",  $event);
templates2events("/etc/openvpn/host-to-net.pool",  $event);


#--------------------------------------------------
# actions for validator vpn-create
#--------------------------------------------------

validator_actions('vpn-create', qw(
                  uniq-account 20
));


#--------------------------------------------------
# actions for certificate-update event
#--------------------------------------------------

$event = "certificate-update";

event_actions($event,
    'nethserver-openvpn-crl' => '30',
);

templates2events("/var/lib/nethserver/certs/ca.cnf",  $event);

#--------------------------------------------------
# actions for post-restore-config event
#--------------------------------------------------

$event = "post-restore-config";

event_actions($event,
    'nethserver-openvpn-ns6upgrade' => '60',
);


#---------------------------------------------------------
# actions for openvpn-tunnel-{create,modify,delete} events
#---------------------------------------------------------

event_actions('openvpn-tunnel-create',
    'nethserver-openvpn-tunnels' => '30',
    'nethserver-openvpn-net2net' => '40',
    'firewall-adjust' => '80',
);
templates2events("/etc/openvpn/host-to-net.pool",  'openvpn-tunnel-create');

event_actions('openvpn-tunnel-modify',
    'nethserver-openvpn-tunnels' => '30',
    'nethserver-openvpn-net2net' => '40',
    'firewall-adjust' => '80',
);
templates2events("/etc/openvpn/host-to-net.pool",  'openvpn-tunnel-modify');

event_actions('openvpn-tunnel-delete',
    'nethserver-openvpn-tunnels' => '30',
    'nethserver-openvpn-net2net' => '40',
    'firewall-adjust' => '80',
);
templates2events("/etc/openvpn/host-to-net.pool",  'openvpn-tunnel-delete');

#--------------------------------------------------
# actions for openvpn-tunnel-upload event
#--------------------------------------------------

event_actions('openvpn-tunnel-upload',
    'nethserver-openvpn-upload-client' => '30',
    'firewall-adjust' => '80',
);

#
# event otp-save
#
$event = 'otp-save';
event_actions($event,
    'nethserver-openvpn-otp' => '10',
);

# restore otp with post-restore-databases

$event = 'post-restore-data';
event_actions($event,
    'nethserver-openvpn-otp' => '10',
);
