#!/bin/sh

mode=$(/sbin/e-smith/config getprop openvpn@host-to-net Mode)

if [ $mode != "bridged" ]; then
    exit 0
fi

br=$(/sbin/e-smith/config getprop openvpn@host-to-net BridgeName)
tap=$(/sbin/e-smith/config getprop openvpn@host-to-net TapInterface)
/usr/sbin/openvpn --rmtun --dev $tap
