#!/bin/sh

# Reset RoadWarrior pending changes
/usr/bin/rm -f /var/spool/openvpn/road-warrior-lock

mode=$(/sbin/e-smith/config getprop openvpn@host-to-net Mode)

if [ $mode != "bridged" ]; then
    exit 0
fi

br=$(/sbin/e-smith/config getprop openvpn@host-to-net BridgeName)

tap=$(/sbin/e-smith/config getprop openvpn@host-to-net TapInterface)

/usr/sbin/openvpn --mktun --dev $tap

/usr/sbin/brctl show | grep -q $tap
if [ $? -ne 0 ]; then
    /usr/sbin/brctl addif $br $tap
fi

/sbin/ifconfig $tap 0.0.0.0 up
