#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

DIR=/var/lib/nethserver/openvpn-tunnels/keys

name=$1
output=$2

if [ -z $name ]; then
    echo "Missing server name"
    exit 1
fi
if [ -z $output ]; then
    echo "Missing destination file name"
    exit 1
fi

if [ ! -f $DIR/$name.crt ]; then
    echo "Certificate for server $name not found"
    exit 1
fi

# Certificate order matters!
cat $DIR/$name.key $DIR/$name.crt $DIR/ca.crt > $output
