#!/usr/bin/env python

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sqlite3

try:
    conn = sqlite3.connect('/var/lib/nethserver/openvpn/connections.db')
    c = conn.cursor()

    env = os.environ
    common_name = env['common_name']
    virtual_ip_addr = env['ifconfig_pool_remote_ip']
    remote_ip_addr = env['untrusted_ip']
    start_time = int(env['time_unix'])

    c.execute("INSERT INTO connections (common_name, virtual_ip_addr, remote_ip_addr, start_time) VALUES (?, ?, ?, ?)", (common_name, virtual_ip_addr, remote_ip_addr, start_time))

    conn.commit()
    conn.close()
finally:
    # this script shouldn't prevent VPN connection, so a potential error code is never returned
    exit(0)
