#!/bin/bash
#
# exit 1 if the user try to connect with a username that doesn't match 
# the common name of the certificate, else exit 0. It enforce security
# this plugin is not used when the authMode is password or certificate

AUTHMODE=$(/usr/sbin/e-smith/config getprop openvpn@host-to-net AuthMode)
LONG=$username@$(/usr/sbin/e-smith/config get DomainName)

if [[ $AUTHMODE = 'certificate' || $AUTHMODE = 'password' ]];then
    exit 0
fi

if [[ $username = $common_name ]];then
    exit 0
elif [[ $LONG = $common_name ]]; then 
    exit 0
fi

exit 1
