#!/usr/bin/perl

use esmith::ConfigDB;
use NetAddr::IP;
my $path = "/etc/openvpn/ccd";

sub write_route($) {
    my $acc = shift;
    my $OUT = '';
    my $outFile = $path . "/" . $acc->key;
    my %props = $acc->props;

    if ($props{'type'} eq 'vpn') {
         if (!defined($props{VPNRemoteNetwork}) || $props{VPNRemoteNetwork} eq '') {
             return;
         }

         $OUT .= "iroute " . $props{VPNRemoteNetwork} . " " . $props{VPNRemoteNetmask} . "\n";
    } elsif ($props{'type'} eq 'openvpn-tunnel-server') {
         if (!defined($props{RemoteNetworks}) || $props{RemoteNetworks} eq '') {
             return;
         }
        
        foreach (split(',',$props{'RemoteNetworks'})) {
            my $net = NetAddr::IP->new($_);
            $OUT .= sprintf("iroute %s %s\n",$net->addr(),$net->mask());
        }
    }

    open (FILE, ">$outFile");
    print FILE $OUT;
    close FILE;
}

my $adb = esmith::ConfigDB->open_ro('vpn') or die "Couldn't open VPN DB\n";

# clean dir
unlink (glob("$path/*")); 

# create ccd config files for vpn accounts
for my $acc ( $adb->get_all() )
{
    my $type = $acc->prop('type');
    if ($type eq 'vpn' || $type eq 'openvpn-tunnel-server') {
        write_route($acc);
    }
}
