#!/usr/bin/perl
#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Fix good ownership and permissions to client
# certificates. This script could be removed later
# the action nethserver-openvpn-upload-client set
# permission in consideration now.
# NethServer/dev#5569

use strict;
use warnings;

my ($login,$pass,$uid,$gid) = getpwnam('srvmgr') or die "srvmgr not in passwd file";
my @files = glob('/var/lib/nethserver/certs/clients/*');
chown $uid, $gid, @files;
chmod 0640, @files;

