#!/usr/bin/perl

use esmith::ConfigDB;
my $path = "/etc/openvpn/ccd";

sub write_route($) {
    my $acc = shift;
    my $OUT = '';
    my $outFile = $path . "/" . $acc->key;
    my %props = $acc->props;
    $props{VPNRemoteNetwork} ||= '';
    $props{VPNRemoteNetmask} ||= '';

    next unless ($props{VPNRemoteNetwork} ne '');

    $OUT .= "iroute " . $props{VPNRemoteNetwork} . " " . $props{VPNRemoteNetmask} . "\n";


    open (FILE, ">$outFile");
    print FILE $OUT;
    close FILE;
}

my $adb = esmith::ConfigDB->open_ro('vpn') or die "Couldn't open VPN DB\n";

# clean dir
unlink (glob("$path/*")); 

# create ccd config files for vpn accounts
for my $acc ( $adb->get_all_by_prop('type' => 'vpn') )
{
    write_route($acc);
}
# create ccd config files for user accounts
for my $user ( $adb->get_all_by_prop('type' => 'vpn-user') )
{
    write_route($user);
}
