#!/bin/bash

event=$1
name=$2

if [ -z $name ]; then
    exit 1
fi

if [ -f /etc/openvpn/$name.conf ]; then
    rm -f /etc/openvpn/$name.conf
fi
if [ -f /etc/openvpn/$name.auth ]; then
    rm -f /etc/openvpn/$name.auth
fi
if [ -f /var/lib/nethserver/certs/clients/$name.pem ]; then
    rm -f /var/lib/nethserver/certs/clients/$name.pem
fi
systemctl stop openvpn@$name
systemctl -f disable openvpn@$name
rm -f "/etc/systemd/system/openvpn@.service.d/"$name".conf"
