#!/usr/bin/env python

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sqlite3
import os


def create_connections_db():
    conn = sqlite3.connect(DATABASE_PATH)
    c = conn.cursor()
    c.execute('''CREATE TABLE connections
				 (common_name text, virtual_ip_addr text, remote_ip_addr text, start_time integer, duration integer, bytes_received integer, bytes_sent integer)''')
    c.execute("CREATE INDEX idx_common_name ON connections (common_name)")
    conn.commit()
    conn.close()


DATABASE_PATH = '/var/lib/nethserver/openvpn/connections.db'
database_exists = os.path.isfile(DATABASE_PATH)

if not database_exists:
    create_connections_db()
    print('[NOTICE] Created roadwarrior connections database {}'.format(DATABASE_PATH))
else:
    # ensure connections table exists
    conn = sqlite3.connect(DATABASE_PATH)
    c = conn.cursor()
    output = c.execute(
        '''SELECT name FROM sqlite_master WHERE type="table" AND name="connections"''')
    table_exists = False
    output = output.fetchone()

    if output and output[0] == 'connections':
        table_exists = True

    if not table_exists:
        create_connections_db()
        print('Created roadwarrior connections database {}'.format(DATABASE_PATH))
