#!/usr/bin/perl

#
# Enable and disable bridge for OpenVPN
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#


use esmith::NetworksDB;
use esmith::ConfigDB;
use strict;

my $idb = esmith::NetworksDB->open();
my $cdb = esmith::ConfigDB->open_ro();
my $openvpn = $cdb->get('openvpn');
my $mode = $openvpn->prop('Mode') || 'routed';
my $role = $openvpn->prop('BridgeRole') || 'green';
my $br_name = $openvpn->prop('BridgeName') || 'br0';

my $device = $idb->get_by_role($role) || die("No $role device found");
my $device_type = $device->prop('type');

if ($mode eq 'bridged' && $device_type ne 'bridged') {
   # A bridge is needed:
   #   - create a bridge with green role
   #   - attach current green ethernet to the bridge

   my $bridge = $idb->new_record($br_name, {
       type => 'bridge',
       device => $br_name,
       bootproto => $device->prop('bootproto'),
       ipaddr => $device->prop('ipaddr'),
       netmask => $device->prop('netmask'),
       gateway => $device->prop('gateway') || '',
       onboot => 'yes',
       role => $role
   });

   
   $idb->set_prop($device->key, 'role', 'bridged');
   $idb->set_prop($device->key, 'bridge', 'br0');
   $device->delete_prop('ipaddr');
   $device->delete_prop('netmask');
   $device->delete_prop('bootproto');
   $device->delete_prop('gateway');

   system('/sbin/e-smith/signal-event interface-update');
} 

