#!/bin/bash

#
# Copyright (C) 2014 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see .
#

# OpenVPN pki initialization

cdir=/var/lib/nethserver/certs

if [ ! -f ${cdir}/serial ]; then
    echo 01 > ${cdir}/serial
fi
if [ ! -f ${cdir}/crlnumber ]; then
    echo 01 > ${cdir}/crlnumber
fi
if [ ! -f ${cdir}/certindex.attr ]; then
    touch ${cdir}/certindex.attr
fi
if [ ! -f ${cdir}/certindex ]; then
    touch ${cdir}/certindex
fi
if [ ! -f ${cdir}/dh1024.pem ]; then
    /usr/bin/openssl dhparam -out ${cdir}/dh1024.pem 1024 2> /dev/null
fi
if [ ! -f ${cdir}/crl.pem ]; then
     /usr/bin/openssl ca -gencrl -out ${cdir}/crl.pem -config ${cdir}/ca.cnf
fi

chmod o+r ${cdir}/{serial,crlnumber,certindex.attr,certindex,dh1024.pem,crl.pem}


# Initialize openvpn-tunnels certs
# Copy certificate to avoid problems on regeneration

tdir=/var/lib/nethserver/openvpn-tunnels

if [ ! -f ${tdir}/dh1024.pem ]; then
    /bin/cp -p ${cdir}/dh1024.pem ${tdir}
    /bin/cp -p /etc/pki/tls/certs/NSRV.crt ${tdir}
    /bin/cp -p /etc/pki/tls/certs/NSRV.key ${tdir}
fi
